https://github.com/RanjitReddy/free-for-dev
https://github.com/RanjitReddy?tab=repositories
====================================================
https://www.codewithjason.com/getting-started-with-angular-and-rails/
https://stackoverflow.com/questions/18369592/modify-ruby-hash-in-place-rails-strong-params
https://medium.com/rails-ember-beyond/ajax-file-upload-in-rails-using-dropzone-and-carrierwave-6f5436fdfdb0
https://github.com/scaffeinate/dropzone-rails-demo
https://shrouded-beyond-2562.herokuapp.com/
https://www.w3resource.com/javascript/form/phone-no-validation.phpg
https://medium.com/@mackenziechild/how-you-can-finally-learn-to-build-stuff-with-rails-eff61e7bcb6f
https://medium.freecodecamp.org/every-time-you-build-a-to-do-list-app-a-puppy-dies-505b54637a5d
https://www.justinweiss.com/articles/how-to-select-database-records-in-an-arbitrary-order/
https://github.com/alexreisner/geocoder
https://www.bountysource.com/
https://www.codementor.io/community
https://www.rubytapas.com/***
https://intellipaat.com/tutorial/salesforce-tutorial/
https://richonrails.com/articles/mongodb-and-rails
http://kerrizor.com/blog/2014/04/02/quick-intro-to-mongodb-in-rails
http://www.ganeshkunwar.com.np/2018/01/06/setting-mysql-database-rails-application/
https://medium.com/@jordanstorms/rails-and-mongodb-the-first-attempt-955e1974f664
============================================================================================
Allow only numeric or decimal input in textbox using jQuery - JSFiddle
https://jsfiddle.net/Behseini/ue8gj52t/
============================================================================================
https://www.spencerdixon.com/blog/image-preview-with-carrierwave-and-rails.html
https://thinkster.io/tutorials/angular-rails
-----------------------------------------------------------------------------------------
showing entries will_paginate
http://www.rubydoc.info/github/mislav/will_paginate/WillPaginate/ViewHelpers
http://www.rubydoc.info/github/mislav/will_paginate/WillPaginate/Collection
will_paginate pagination styles
http://mislav.github.io/will_paginate/
===========================================================================================
https://www.learnenough.com/action-cable-tutorial
https://stackoverflow.com/questions/16319008/get-nested-form-field-id-number-from-cocoon
https://hasjob.co/epmservices.biz/ymzl9
https://jacopretorius.net/2017/04/validate-uniqueness-in-rails.html
http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_uniqueness_of
https://www.engineyard.com/blog/
https://iridakos.com/tutorials/2017/12/03/elasticsearch-and-rails-tutorial.html
https://revs.runtime-revolution.com/working-with-facebook-using-devise-omniauth-koala-and-rails-5-cde5d032de02
-------------------------------------------------------------------------------------------
selecting multiple fields inside cocoon nested field
https://stackoverflow.com/questions/18131386/multi-select-file-upload-field-with-nested-attributes-in-rails
============================================================================================
https://stackoverflow.com/questions/594325/truncate-leading-zeros-of-a-string-in-javascript
https://www.ibm.com/developerworks/
https://ieeexplore.ieee.org/Xplore/home.jsp
https://devblast.com/start
https://www.coursera.org/learn/ruby-on-rails-web-services-mongodb
https://scotch.io/tutorials/build-a-restful-json-api-with-rails-5-part-one
https://try.github.io/levels/1/challenges/1
============================================================================================
http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html
https://www.sitepoint.com/learn-the-first-best-practices-for-rails-and-rspec/
============================================================================================
Converting Date format from
2018-04-25 00:00:00 UTC to 2018-04-25 by date.strftime("%Y-%m-%d")
https://stackoverflow.com/questions/25403683/removing-eg-utc-0100-0200-seconds-from-the-timezone-rails
============================================================================================
http://rspec.info/
https://medium.mybridge.co/learn-react-js-from-top-45-tutorials-for-the-past-year-v-2018-28b7f4d4b2c4
https://www.theodinproject.com/courses/ruby-on-rails/lessons/active-record-associations
https://skillcrush.com/2014/05/08/17-awesome-ruby-programming-language/
https://esausilva.com/2016/01/29/move-items-between-two-listbox-using-jquery-html-select-tag/
https://blog.cloud66.com/supercharge-rails-with-vuejs-and-actioncables/
https://github.com/cloud66-samples/rails-5-actioncable-example
https://mkdev.me/en/posts/rails-5-vue-js-how-to-stop-worrying-and-love-the-frontend
https://blog.codeship.com/vuejs-as-a-frontend-for-rails/
============================================================================================
http://learnruby.com/code.html
https://rubygarage.org/
https://rubygarage.org/blog/how-to-interview-your-ruby-on-rails-developer
https://medium.freecodecamp.org/how-i-landed-a-full-stack-developer-job-without-a-tech-degree-or-work-experience-6add97be2051
============================================================================================
http://www.betterspecs.org/
http://www.nascenia.com/ruby-on-rails-application-testing-using-rspec/
http://www.nascenia.com/how-to-integrate-elasticsearch-in-your-rails-application/
https://www.sitepoint.com/full-text-search-rails-elasticsearch/
https://www.theodinproject.com/courses
https://www.sitepoint.com/model-view-controller-mvc-architecture-rails/
https://www.engineyard.com/
https://www.engineyard.com/blog/using_form_with-vs-form_for-vs-form_tag
https://rubyinrails.com/2014/03/17/what-is-attr_accessor-in-rails/
https://rubyinrails.com/
https://www.sitepoint.com/generate-excel-spreadsheets-rails-axlsx-gem/
===========================================================================================
https://medium.com/programming-problem-solving-logbook/rails-multiple-checkboxes-e9c4c7fda356
https://stackoverflow.com/questions/9400736/passing-rails-variable-in-a-onclick-function-of-check-box-tag
============================================================================================
https://www.quora.com/in/Where-can-I-find-practice-exercises-problems-for-Ruby-and-Rails
http://www.codequizzes.com
============================================================================================
https://deepakrip007.wordpress.com/2013/10/04/implementing-data-table-in-rails/
https://deepakrip007.wordpress.com/2013/11/05/google-integration-using-devise-and-omniauth-in-rails-app/
============================================================================================
https://thinkster.io/tutorials/fullstack
http://www.bradoncode.com/tutorials/learn-mean-stack-tutorial/
https://medium.com/aviabird/guide-to-install-mongodb-on-ubuntu-14-04-9ed292dc53f6
============================================================================================
https://learndigital.withgoogle.com/digitalunlocked/?dclid=CLriz7qft9oCFQgeaAodQAADQQ&gclid=EAIaIQobChMIvOzukp-32gIVxo5oCh0yPwLpEAEYASAAEgK2JfD_BwE
============================================================================================
http://www.rubydoc.info/github/CanCanCommunity/cancancan/CanCan/Ability
https://app.codility.com-->online ruby interview tests
